#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SERVER_PORT 8080
#define CPU_NUMBER 0

#define MAX_CLIENTS 25
#define BACKLOG_SIZE 5
#define NET_BUFFER_SIZE 4096
#define NET_RESPONSE_BUF_SIZE 4096

#define N_TASKS 3
#define MAX_INSTANCES 20
#define MAX_QUEUE_SIZE 20
#define TASK_NAME_LEN 32

#endif
